"""Shared paths, file grammars and the per-portfolio contracts.

Everything more than one builder reads lives here, so a grammar is defined once:
the A-Z grid CSV, the hand-edited yes/no switch JSON, statement.json,
constraints.json, screen/invalid.csv and the portfolio's anchor date.

statement.json -- one per portfolio, hand-edited (or written by the UI):

    {
      "approach": "free text, discretionary reference only",
      "scope":    "free text, discretionary reference only",
      "holdings": {"min": 20, "max": 30},
      "rebalance": {"frequency": "1Q", "drift_threshold": 0.08},
      "screens": {
        "turnover":  {"on": false, "min_pct": 0.10},
        "float_cap": {"on": false, "min_bn_vnd": 1000}
      }
    }

    holdings   integers, 1 <= min <= max. target.py WARNs outside the range.
    rebalance  frequency is "2W" | "1M" | "1Q" | null; drift_threshold is a
               FRACTION (0.08 = 8%) or null; at least one must be set. Drift is
               half the sum of absolute weight gaps at group grain. Consumed by
               the rebalance stage, not by any builder yet.
    screens    turnover: average daily turnover over 21 sessions as % of float
               cap, params.turnover_21_pct. float_cap: params.float_cap in
               billions of VND. A screen that is off is never evaluated.
               FOL is deferred and not accepted yet.

constraints.json -- one per portfolio, hand-edited (or written by the UI). A
missing file means every constraint is off. All values are FRACTIONS of the book.

    {
      "sector": {"on": false, "max": 0.25, "per_group": {"Banks - Private": 0.30}},
      "stock":  {"on": false, "max": 0.10},
      "large":  {"on": false, "threshold": 0.05, "aggregate": 0.40}
    }

    sector  cap on every live group's weight; per_group overrides max for the
            named groups, tactical groups included. Universal = empty per_group.
    stock   cap on every holding's weight.
    large   UCITS style: holdings above threshold may sum to at most aggregate.
            threshold <= aggregate.
    The solver lives in target.py (apply_constraints); read its docstring.

backtest_config.json -- one per portfolio, written by the desk's Backtest tab
(or by hand). Trading assumptions for scr/backtest_engine.py only; the
rebalance mandate stays in statement.json. A missing file means the defaults.

    {"brokerage_bps": 10, "sell_tax_bps": 10, "lag_sessions": 1,
     "risk_free_rate": 0.06}

    brokerage_bps   per side, >= 0          sell_tax_bps  on sells, >= 0
    lag_sessions    integer 0-5: fill this many sessions after the decision
    risk_free_rate  FRACTION a year in [0, 1), used for Sharpe only

screen/invalid.csv -- names invalidated by `portfolio.py screen --invalidate`.
ticker, group, screen, value, threshold, invalidated_at. Written by the CLI/UI,
never regenerated by a screen run. An invalidated name stays in the baseline
grid (it is still part of the book universe) but can never be investable or
claimed by a tactical group; target.py FAILs if it is.

The portfolio's anchor is the anchor_date line of input/forked_from.txt. Each
portfolio sits on its own baseline, portfolio/baseline/<anchor>/.

Freshness -- every derived file is stale when an input it was built from is
newer, by file time (newer_than). The chain the scripts and the UI both check:

    fiinpro drops ─┐
                   ├─> market.db ─> params/<anchor>.csv ─> baseline/<anchor>/
    group_map_live.csv, fol.csv ─┘   (params reads them)
                                  ─> portfolio/<name>/input/  (compared by content)
"""
import csv
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DB = DATA / "market.db"
PARAMS = DATA / "params"
INDEX = ROOT / "index"
ANCHOR_CFG = INDEX / "anchor_date.json"
GROUP_MAP = INDEX / "group_map_live.csv"
PORTFOLIO = ROOT / "portfolio"

# File names are shared with scr/backtest.py; do not rename.
GRID = "sector_constituents.csv"
ALLOC = "sector_allocation.csv"
BOOK = "sector_constituents_custom.csv"
CAP = "sector_cap.json"
TAC = "tactical_group.csv"
TAC_SWITCH = "tactical_group.json"
STATEMENT = "statement.json"
CONSTRAINTS = "constraints.json"
BT_CONFIG = "backtest_config.json"
INVALID = "invalid.csv"            # under portfolio/<name>/screen/
FORKED = "forked_from.txt"         # under portfolio/<name>/input/

FREQUENCIES = ("2W", "1M", "1Q")
SCREENS = {"turnover": "min_pct", "float_cap": "min_bn_vnd"}


def newer_than(target: Path, *inputs: Path) -> list[Path]:
    """Inputs that exist and are newer than target; every existing input if
    target is missing. Empty means target is fresh."""
    have = [p for p in inputs if p is not None and p.exists()]
    if not target.exists():
        return have
    t = target.stat().st_mtime
    return [p for p in have if p.stat().st_mtime > t]


class BookError(Exception):
    """A fatal, already-worded message for the person editing a portfolio.

    Scripts print it as `FAIL  <message>`; embed "\\n      " for a hint line.
    """


def read_grid(path: Path) -> list[list[str]]:
    # utf-8-sig + trailing-blank strip: Excel leaves BOMs and pads or trims
    # trailing empty cells unpredictably. Both sides of every comparison go
    # through here, so the normalisation cancels out.
    with open(path, encoding="utf-8-sig", newline="") as f:
        rows = [[c.strip() for c in r] for r in csv.reader(f)]
    for r in rows:
        while r and r[-1] == "":
            r.pop()
    while rows and not rows[-1]:
        rows.pop()
    return rows


def write_grid(path: Path, header: list[list[str]],
               columns: list[list[str]]) -> None:
    """Write rows 0-2 verbatim, then the ragged columns blank-padded."""
    depth = max((len(c) for c in columns), default=0)
    with open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        for row in header:
            w.writerow(row)
        for i in range(depth):
            w.writerow([c[i] if i < len(c) else "" for c in columns])


def grid_column(rows: list[list[str]], j: int) -> list[str]:
    """Non-blank tickers of column j, rows 3+. Blanks are deletions."""
    return [r[j] for r in rows[3:] if j < len(r) and r[j]]


def read_switch(path: Path, key: str) -> tuple[bool, dict]:
    """Parse a hand-edited on/off JSON. A missing file is "no"."""
    if not path.exists():
        return False, {}
    try:
        cfg = json.loads(path.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise BookError(f"{path.name} is not readable JSON: {e}")
    if not isinstance(cfg, dict):
        raise BookError(f"{path.name}: expected a JSON object")
    v = cfg.get(key, "no")
    if isinstance(v, bool):
        return v, cfg
    if isinstance(v, str) and v.strip().lower() in ("yes", "no"):
        return v.strip().lower() == "yes", cfg
    raise BookError(f"{path.name}: {key} is {v!r}, want \"yes\" or \"no\"")


def default_statement() -> dict:
    return {
        "approach": "",
        "scope": "",
        "holdings": {"min": 20, "max": 30},
        "rebalance": {"frequency": "1Q", "drift_threshold": None},
        "screens": {"turnover": {"on": False, "min_pct": 0.10},
                    "float_cap": {"on": False, "min_bn_vnd": 1000}},
    }


def validate_statement(s: dict) -> dict:
    """Return the statement if valid; raise BookError naming the first fault."""
    where = STATEMENT
    if not isinstance(s, dict):
        raise BookError(f"{where}: expected a JSON object")
    for k in ("approach", "scope"):
        if not isinstance(s.get(k, ""), str):
            raise BookError(f"{where}: {k} must be text")

    h = s.get("holdings")
    if not isinstance(h, dict):
        raise BookError(f"{where}: holdings must be {{\"min\": .., \"max\": ..}}")
    lo, hi = h.get("min"), h.get("max")
    if not (isinstance(lo, int) and isinstance(hi, int)
            and not isinstance(lo, bool) and 1 <= lo <= hi):
        raise BookError(f"{where}: holdings min/max must be integers with "
                        f"1 <= min <= max, got {lo!r}, {hi!r}")

    r = s.get("rebalance")
    if not isinstance(r, dict):
        raise BookError(f"{where}: rebalance must be an object")
    freq, drift = r.get("frequency"), r.get("drift_threshold")
    if freq is not None and freq not in FREQUENCIES:
        raise BookError(f"{where}: rebalance.frequency {freq!r}, want one of "
                        f"{list(FREQUENCIES)} or null")
    if drift is not None and (isinstance(drift, bool)
                              or not isinstance(drift, (int, float))
                              or not 0 < drift < 1):
        raise BookError(f"{where}: rebalance.drift_threshold {drift!r} must "
                        "be a fraction in (0, 1), e.g. 0.08 for 8%")
    if freq is None and drift is None:
        raise BookError(f"{where}: rebalance needs a frequency, a "
                        "drift_threshold, or both")

    sc = s.get("screens", {})
    if not isinstance(sc, dict):
        raise BookError(f"{where}: screens must be an object")
    unknown = sorted(set(sc) - set(SCREENS))
    if unknown:
        raise BookError(f"{where}: unknown screen(s) {unknown}; available "
                        f"{sorted(SCREENS)} (FOL is deferred)")
    for name, key in SCREENS.items():
        cfg = sc.get(name, {"on": False})
        if not isinstance(cfg.get("on", False), bool):
            raise BookError(f"{where}: screens.{name}.on must be true or false")
        if cfg.get("on"):
            v = cfg.get(key)
            if isinstance(v, bool) or not isinstance(v, (int, float)) or v < 0:
                raise BookError(f"{where}: screens.{name}.{key} must be a "
                                f"non-negative number, got {v!r}")
    return s


def _read_json(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise BookError(f"{p.name} is not readable JSON: {e}")


def load_statement(home: Path) -> dict | None:
    """The portfolio's statement, validated; None if the file is absent."""
    p = home / STATEMENT
    if not p.exists():
        return None
    return validate_statement(_read_json(p))


def default_constraints() -> dict:
    return {
        "sector": {"on": False, "max": 0.25, "per_group": {}},
        "stock": {"on": False, "max": 0.10},
        "large": {"on": False, "threshold": 0.05, "aggregate": 0.40},
    }


def _fraction(v, where: str, upper_open: bool = False) -> float:
    ok = (not isinstance(v, bool) and isinstance(v, (int, float))
          and math.isfinite(v) and 0 < v and (v < 1 if upper_open else v <= 1))
    if not ok:
        rng = "(0, 1)" if upper_open else "(0, 1]"
        raise BookError(f"{CONSTRAINTS}: {where} {v!r} must be a fraction in "
                        f"{rng}, e.g. 0.25 for 25%")
    return float(v)


def validate_constraints(c: dict) -> dict:
    """Return constraints with every block present; raise BookError on a fault."""
    if not isinstance(c, dict):
        raise BookError(f"{CONSTRAINTS}: expected a JSON object")
    base = default_constraints()
    unknown = sorted(set(c) - set(base))
    if unknown:
        raise BookError(f"{CONSTRAINTS}: unknown block(s) {unknown}; "
                        f"available {sorted(base)}")
    out = {}
    for block, dflt in base.items():
        cfg = c.get(block, {"on": False})
        if not isinstance(cfg, dict):
            raise BookError(f"{CONSTRAINTS}: {block} must be an object")
        extra = sorted(set(cfg) - set(dflt))
        if extra:
            raise BookError(f"{CONSTRAINTS}: {block} has unknown key(s) {extra}")
        on = cfg.get("on", False)
        if not isinstance(on, bool):
            raise BookError(f"{CONSTRAINTS}: {block}.on must be true or false")
        out[block] = {**dflt, **cfg, "on": on}
    s, st, lg = out["sector"], out["stock"], out["large"]
    if s["on"]:
        s["max"] = _fraction(s["max"], "sector.max")
        if not isinstance(s["per_group"], dict):
            raise BookError(f"{CONSTRAINTS}: sector.per_group must map group "
                            "name -> fraction")
        s["per_group"] = {g: _fraction(v, f"sector.per_group[{g!r}]")
                          for g, v in s["per_group"].items()}
    if st["on"]:
        st["max"] = _fraction(st["max"], "stock.max")
    if lg["on"]:
        lg["threshold"] = _fraction(lg["threshold"], "large.threshold", upper_open=True)
        lg["aggregate"] = _fraction(lg["aggregate"], "large.aggregate")
        if lg["threshold"] > lg["aggregate"]:
            raise BookError(f"{CONSTRAINTS}: large.threshold {lg['threshold']} "
                            f"exceeds large.aggregate {lg['aggregate']}")
    return out


def load_constraints(home: Path) -> dict:
    """The portfolio's constraints, validated; all off if the file is absent."""
    p = home / CONSTRAINTS
    return validate_constraints(_read_json(p) if p.exists() else default_constraints())


def default_backtest_config() -> dict:
    return {"brokerage_bps": 10.0, "sell_tax_bps": 10.0, "lag_sessions": 1,
            "risk_free_rate": 0.06}


def validate_backtest_config(c: dict) -> dict:
    """Return the config with every key present; raise BookError on a fault."""
    if not isinstance(c, dict):
        raise BookError(f"{BT_CONFIG}: expected a JSON object")
    base = default_backtest_config()
    unknown = sorted(set(c) - set(base))
    if unknown:
        raise BookError(f"{BT_CONFIG}: unknown key(s) {unknown}; available {sorted(base)}")
    out = {**base, **c}

    def number(v):
        return not isinstance(v, bool) and isinstance(v, (int, float)) and math.isfinite(v)

    for k in ("brokerage_bps", "sell_tax_bps"):
        if not number(out[k]) or out[k] < 0:
            raise BookError(f"{BT_CONFIG}: {k} {out[k]!r} must be a number >= 0 (bps)")
        out[k] = float(out[k])
    lag = out["lag_sessions"]
    if isinstance(lag, bool) or not isinstance(lag, int) or not 0 <= lag <= 5:
        raise BookError(f"{BT_CONFIG}: lag_sessions {lag!r} must be an integer 0-5")
    rf = out["risk_free_rate"]
    if not number(rf) or not 0 <= rf < 1:
        raise BookError(f"{BT_CONFIG}: risk_free_rate {rf!r} must be a fraction in "
                        "[0, 1), e.g. 0.06 for 6%")
    out["risk_free_rate"] = float(rf)
    return out


def load_backtest_config(home: Path) -> dict:
    """The portfolio's backtest config, validated; defaults if the file is absent."""
    p = home / BT_CONFIG
    return validate_backtest_config(_read_json(p) if p.exists() else {})


def portfolio_anchor(home: Path) -> str:
    """ISO anchor date the portfolio was forked on, from input/forked_from.txt."""
    p = home / "input" / FORKED
    if not p.exists():
        raise BookError(f"missing {p}\n      run scr/portfolio.py fork {home.name}")
    for line in p.read_text(encoding="utf-8-sig").splitlines():
        key, _, val = line.partition(":")
        if key.strip() == "anchor_date" and val.strip():
            return val.strip()
    raise BookError(f"{p} has no anchor_date line; re-run scr/portfolio.py "
                    f"fork {home.name}")


def read_invalid(home: Path) -> list[str]:
    """Sorted invalidated tickers; empty if screen/invalid.csv is absent."""
    p = home / "screen" / INVALID
    if not p.exists():
        return []
    with open(p, encoding="utf-8-sig", newline="") as f:
        return sorted({r["ticker"].strip() for r in csv.DictReader(f)
                       if r.get("ticker", "").strip()})
